name = "GAPGroups"
uuid = "21fe2a1e-8ea0-11e9-0a1a-b318e3c68493"
authors = ["Max Horn"]
version = "0.1.0"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"

[compat]
GAP = "0.2.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
